name: publish

on: 
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'tag name'     
        required: true

env:
  RUNID: 613573412

jobs:
  windows:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build_v8.yml
          name: v8_bin
          path: unity/native_src/
      - name: Build
        run: |
          cd unity\native_src
          .\make_win64.bat
          .\make_win32.bat
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./unity/Assets/Plugins/**/*
          name: Unity_Plugins_V8
  windows_qjs:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build_quickjs.yml
          #run_id: ${{env.RUNID}}
          name: qjs_v8_bin
          path: unity/native_src/
      - name: Build
        run: |
          cd unity\native_src
          .\make_win64_qjs.bat
          .\make_win32_qjs.bat
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./unity/Assets/Plugins/**/*
          name: Unity_Plugins_Quickjs
  publish:
    runs-on: ubuntu-latest
    needs: [windows,windows_qjs]
    steps:
      - uses: actions/checkout@v2
      
      - name: Retrieve version
        run: |
          echo "PLUGIN_VERSION=$(cat unity/native_src/Src/Puerts.cpp | grep -Po '(?<=LIB_VERSION\s)(\d+)')" >> $GITHUB_ENV
            
      - uses: actions/download-artifact@v1
        with:
          name: Unity_Plugins_V8
          path: V8/Plugins/
          
      - uses: actions/download-artifact@v1
        with:
          name: Unity_Plugins_Quickjs
          path: Quickjs/Plugins/
          
      - name: Create Release Asset
        run: |
          cd V8/ && tar cvfz ../Plugins_V8_ver${{ env.PLUGIN_VERSION }}.tgz Plugins && cd -
          cd Quickjs/ && tar cvfz ../Plugins_Quickjs_ver${{ env.PLUGIN_VERSION }}.tgz Plugins && cd -
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          release_name: Tag:${{ github.event.inputs.tag_name }},Plugin_Version:${{ env.PLUGIN_VERSION }}
          draft: false
          prerelease: false
          
      - name: Upload V8 Plugins
        #id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Plugins_V8_ver${{ env.PLUGIN_VERSION }}.tgz
          asset_name: Plugins_V8_ver${{ env.PLUGIN_VERSION }}.tgz
          asset_content_type: application/tgz
          
      - name: Upload Quickjs Plugins
        #id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Plugins_Quickjs_ver${{ env.PLUGIN_VERSION }}.tgz
          asset_name: Plugins_Quickjs_ver${{ env.PLUGIN_VERSION }}.tgz
          asset_content_type: application/tgz
   
